### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by papakai** [Rashad-j/Hexonet#1]
Dear Rashad,

thanks for providing your solution. :-)

We are missing a step by step guide covered as README.md which should always be part of a project and covering:

* necessary installation steps (virtualenv, venv?)
* how to use the venv
* how to start the application

As we maintain only one python project right now, virtualenv is something new, so we are already curious on how to use it. In addition we are just using python3 (on ubuntu 18) as python2 will be deprecating soon. Please also ensure your code to be python3 compatible if it is not yet.

Very appreciated! If you have questions, just let mw know.

(Don't worry about the time frame, next week Wednesday latest is fine)

Kai Schwarz
HEXONET

**Comment by Rashad-j** [comment]
Dear Kai, 

Thank you for your response. 

My apologies for not adding README.md file. Now it's added to the project.  
You will find a brief explanation of virtual environment and how to use it in python. Also, a step by step installation guide in order to set up the application, virtual environment, and how to start the application. 

Please note that installation steps and running the application on Mac and Windows are similar, except for some minor differences in command such as using python instead of python3 in windows. 

If you have any further issues, then I am happy to answer them.

Warm regards, 

Rashad Jamara.

**Comment by papakai** [comment]
Morning Rashad,

thanks for having that part realized, worked like a charm.

To round your project up, it would make sense to have a .gitignore file covering folders like .idea, venv at least. So folders/files that are coming from IDE or are auto-generated by scripts / tools.
Having them in version control, doesn't make a lot sense.

I've been checking your source code and also the output of your app - looks very good and professional to me. Great work, thanks for it. We will come back to you soon.

Best
Kai
